### ISSUE TITLE
关于jdk以及boat的一些问题。

### ISSUE THREAD

**Issue by by-scott** [longjunyu2/openjdk-aarch64-jdk8u-android#1]
我也在尝试编译jdk，但是我用的是mobile jdk9，只能编译arm32位的，编译64位的话会出现一些我无法解决的问题。我看了cosine的jdk android端项目，似乎是基于jdk8的，但jdk8不是没有mobile版吗？采用交叉编译？我clone下来没办法编译。
另外，我不知道在国内平台如何联系你，我想请教你一些问题：
boat的native库有个server，我始终没办法找到它的入口在哪，是什么在调用它，以及boat.c里的JLI_Launch的实现在哪，我尝试把头文件声明全部注释掉，它也没有报错，所以我在想它是不是在我没办法找到的地方声明、实现的。
这类项目我很感兴趣，通过Google和github我已经很尽力的解决大量其它问题了，但是对于以上问题我仍然没办法得知答案。
我想学习。

**Comment by by-scott** [comment]
还有一个问题是我自己编译的mobile jdk没办法在boat上使用，却可以在boardwalk上使用。一些环境适配已经尽可能的改了却仍然没办法在boat上使用。

**Comment by SnowFuryHQ** [comment]
如果，您想了解我们（和我们一起讨论各种技术性问题）可以加群（854301227）（人不多，都十分友好），有大佬&作者也有菜鸡

**Comment by by-scott** [comment]
> 如果，您想了解我们（和我们一起讨论各种技术性问题）可以加群（854301227）（人不多，都十分友好），有大佬&作者也有菜鸡

感谢你的回复，我正在尝试加群:D

**Comment by SnowFuryHQ** [comment]
您为什么退群啊 ？

**Comment by by-scott** [comment]
> 您为什么退群啊 ？

1、我不是你们团队成员，也不好再打扰你们
2、因为是复读，这次高考对我很重要，但是我对于编程的兴趣很大，如果待在群里我看到有人提问题就会去学习并尝试解决
3、虽然与你们相处的时间很短，但我刚到很开学。谢谢你们的关注和帮助。我不知道高考后会如何，我期待以后能够正式加入你们。
